name: Build Snowstorm
run-name: Create an archive of a new version of Snowstorm.
on: 
  push:
    paths: 'snowstorm/version.json'
  release:
    types: [published]
jobs:
  tar-snowstorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheDoctor0/zip-release
        with:
          type: zip
          filename: Snowstorm.zip
          path: snowstorm
