name: Pack Release
on: 
  release:
    types: [published]
  workflow_dispatch:
jobs:
  compress-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: TheDoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: cog_autobuild.mrpack
          exclusions: '/.github /.vscode /flowcharts changes.txt CONTRACT.md HOSTING.md INSTALLATION.md LICENSE README.md'
      - uses: actions/upload-artifact@v2
        with:
          name: instance
          path: ./cog_autobuild.mrpack
